### ISSUE TITLE
How make it work with ASP Core

### ISSUE THREAD

**Issue by papyr** [optimajet/formbuilder#13]
Hello, how can we make this work with ASP Core Views/pages

**Comment by optimajet** [comment]
@papyr FormBuilder is just a JavaScript library. Use it like all other JavaScript libraries.

**Comment by papyr** [comment]
thanks optima.

Any chance we can get a working sample with ASP core, like a single responsibility pattern on the API CRUD, this could be better than something like CK Editor since it fills a good need.

Also, what is the recommended strategy on saving form to the DB, is it a binary blob, or decomposed parts, should we save the forms columns as a table schema?
