### ISSUE TITLE
has error in the 'npm install '

### ISSUE THREAD

**Issue by Boroushakihbm** [optimajet/formbuilder#20]
hi has error in the 'npm install '

npm install  
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.15.4
npm WARN Found: @babel/core@7.9.6
npm WARN node_modules/@babel/core
npm WARN   dev @babel/core@"7.9.6" from the root project
npm WARN   76 more (@babel/helper-compilation-targets, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.15.4
npm WARN node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm WARN   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.15.4" from @babel/preset-env@7.15.6
npm WARN   node_modules/@babel/preset-env
npm WARN
npm WARN Conflicting peer dependency: @babel/core@7.20.2
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.15.4
npm WARN   node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm WARN     @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.15.4" from @babel/preset-env@7.15.6
npm WARN     node_modules/@babel/preset-env
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-proposal-class-static-block@7.15.4
npm WARN Found: @babel/core@7.9.6
npm WARN node_modules/@babel/core
npm WARN   dev @babel/core@"7.9.6" from the root project
npm WARN   76 more (@babel/helper-compilation-targets, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@"^7.12.0" from @babel/plugin-proposal-class-static-block@7.15.4
npm WARN node_modules/@babel/plugin-proposal-class-static-block
npm WARN   @babel/plugin-proposal-class-static-block@"^7.15.4" from @babel/preset-env@7.15.6
npm WARN   node_modules/@babel/preset-env
npm WARN
npm WARN Conflicting peer dependency: @babel/core@7.20.2
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.12.0" from @babel/plugin-proposal-class-static-block@7.15.4
npm WARN   node_modules/@babel/plugin-proposal-class-static-block
npm WARN     @babel/plugin-proposal-class-static-block@"^7.15.4" from @babel/preset-env@7.15.6
npm WARN     node_modules/@babel/preset-env
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: reflux@6.4.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">=0.14.0" from @hypnosphi/create-react-context@0.3.1
npm ERR!   node_modules/@hypnosphi/create-react-context
npm ERR!     @hypnosphi/create-react-context@"^0.3.1" from react-popper@1.3.11
npm ERR!     node_modules/semantic-ui-react/node_modules/react-popper
npm ERR!       react-popper@"^1.3.3" from semantic-ui-react@0.87.3
npm ERR!       node_modules/semantic-ui-react
npm ERR!         semantic-ui-react@"0.87.3" from the root project
npm ERR!   18 more (@semantic-ui-react/event-stack, draft-convert, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.2" from reflux@6.4.1
npm ERR! node_modules/reflux
npm ERR!   reflux@"6.4.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@15.7.0
npm ERR! node_modules/react
npm ERR!   peer react@"^15.0.2" from reflux@6.4.1
npm ERR!   node_modules/reflux
npm ERR!     reflux@"6.4.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\p.brooshaki\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\p.brooshaki\AppData\Local\npm-cache\_logs\2022-11-09T07_41_07_175Z-debug-0.log

0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@8.11.0
2 info using node@v16.15.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\React prime react sample\ssss\optimajet-formbuilder\demo\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\p.brooshaki\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\p.brooshaki\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install
23 verbose argv "install"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:C:\Users\p.brooshaki\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\p.brooshaki\AppData\Local\npm-cache\_logs\2022-11-09T07_41_07_175Z-debug-0.log
29 timing npm:load:logFile Completed in 6ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 24ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 3 files
35 timing idealTree:init Completed in 698ms
36 timing idealTree:userRequests Completed in 0ms
37 silly idealTree buildDeps
38 timing idealTree:#root Completed in 0ms
39 silly fetch manifest @babel/core@^7.13.0
40 silly logfile error removing log file C:/Users/p.brooshaki/AppData/Local/npm-cache/_logs/2022-10-26T12_36_35_521Z-debug-0.log [Error: EPERM: operation not permitted, lstat 'C:\Users\p.brooshaki\AppData\Local\npm-cache\_logs\2022-10-26T12_36_35_521Z-debug-0.log'] {
40 silly logfile   errno: -4048,
40 silly logfile   code: 'EPERM',
40 silly logfile   syscall: 'lstat',
40 silly logfile   path: 'C:\\Users\\p.brooshaki\\AppData\\Local\\npm-cache\\_logs\\2022-10-26T12_36_35_521Z-debug-0.log'
40 silly logfile }
41 silly logfile done cleaning log files
42 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 3732ms (cache revalidated)
43 warn ERESOLVE overriding peer dependency {
43 warn ERESOLVE   code: 'ERESOLVE',
43 warn ERESOLVE   edge: {
43 warn ERESOLVE     type: 'peer',
43 warn ERESOLVE     name: '@babel/core',
43 warn ERESOLVE     spec: '^7.13.0',
43 warn ERESOLVE     error: 'INVALID',
43 warn ERESOLVE     from: {
43 warn ERESOLVE       name: '@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining',
43 warn ERESOLVE       version: '7.15.4',
43 warn ERESOLVE       location: 'node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining',
43 warn ERESOLVE       isWorkspace: false,
43 warn ERESOLVE       dependents: [Array]
43 warn ERESOLVE     }
43 warn ERESOLVE   },
43 warn ERESOLVE   dep: {
43 warn ERESOLVE     name: '@babel/core',
43 warn ERESOLVE     version: '7.20.2',
43 warn ERESOLVE     whileInstalling: {
43 warn ERESOLVE       name: '@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining',
43 warn ERESOLVE       version: '7.15.4',
43 warn ERESOLVE       path: 'D:\\React prime react sample\\ssss\\optimajet-formbuilder\\demo\\node_modules\\@babel\\plugin-bugfix-v8-spread-parameters-in-optional-chaining'
43 warn ERESOLVE     },
43 warn ERESOLVE     location: 'node_modules/@babel/core',
43 warn ERESOLVE     isWorkspace: false,
43 warn ERESOLVE     dependents: [ [Object] ]
43 warn ERESOLVE   },
43 warn ERESOLVE   current: {
43 warn ERESOLVE     name: '@babel/core',
43 warn ERESOLVE     version: '7.9.6',
43 warn ERESOLVE     location: 'node_modules/@babel/core',
43 warn ERESOLVE     isWorkspace: false,
43 warn ERESOLVE     dependents: [
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
43 warn ERESOLVE       [Object], [Object]
43 warn ERESOLVE     ]
43 warn ERESOLVE   },
43 warn ERESOLVE   peerConflict: {
43 warn ERESOLVE     current: {
43 warn ERESOLVE       name: '@babel/core',
43 warn ERESOLVE       version: '7.9.6',
43 warn ERESOLVE       location: 'node_modules/@babel/core',
43 warn ERESOLVE       isWorkspace: false,
43 warn ERESOLVE       dependents: [Array]
43 warn ERESOLVE     },
43 warn ERESOLVE     peer: {
43 warn ERESOLVE       name: '@babel/core',
43 warn ERESOLVE       version: '7.20.2',
43 warn ERESOLVE       whileInstalling: [Object],
43 warn ERESOLVE       location: 'node_modules/@babel/core',
43 warn ERESOLVE       isWorkspace: false,
43 warn ERESOLVE       dependents: [Array]
43 warn ERESOLVE     }
43 warn ERESOLVE   },
43 warn ERESOLVE   strictPeerDeps: false,
43 warn ERESOLVE   force: false,
43 warn ERESOLVE   isMine: false
43 warn ERESOLVE }
44 timing idealTree:node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining Completed in 3757ms
45 silly fetch manifest @babel/core@^7.12.0
46 warn ERESOLVE overriding peer dependency {
46 warn ERESOLVE   code: 'ERESOLVE',
46 warn ERESOLVE   edge: {
46 warn ERESOLVE     type: 'peer',
46 warn ERESOLVE     name: '@babel/core',
46 warn ERESOLVE     spec: '^7.12.0',
46 warn ERESOLVE     error: 'INVALID',
46 warn ERESOLVE     from: {
46 warn ERESOLVE       name: '@babel/plugin-proposal-class-static-block',
46 warn ERESOLVE       version: '7.15.4',
46 warn ERESOLVE       location: 'node_modules/@babel/plugin-proposal-class-static-block',
46 warn ERESOLVE       isWorkspace: false,
46 warn ERESOLVE       dependents: [Array]
46 warn ERESOLVE     }
46 warn ERESOLVE   },
46 warn ERESOLVE   dep: {
46 warn ERESOLVE     name: '@babel/core',
46 warn ERESOLVE     version: '7.20.2',
46 warn ERESOLVE     whileInstalling: {
46 warn ERESOLVE       name: '@babel/plugin-proposal-class-static-block',
46 warn ERESOLVE       version: '7.15.4',
46 warn ERESOLVE       path: 'D:\\React prime react sample\\ssss\\optimajet-formbuilder\\demo\\node_modules\\@babel\\plugin-proposal-class-static-block'
46 warn ERESOLVE     },
46 warn ERESOLVE     location: 'node_modules/@babel/core',
46 warn ERESOLVE     isWorkspace: false,
46 warn ERESOLVE     dependents: [ [Object] ]
46 warn ERESOLVE   },
46 warn ERESOLVE   current: {
46 warn ERESOLVE     name: '@babel/core',
46 warn ERESOLVE     version: '7.9.6',
46 warn ERESOLVE     location: 'node_modules/@babel/core',
46 warn ERESOLVE     isWorkspace: false,
46 warn ERESOLVE     dependents: [
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object], [Object], [Object], [Object],
46 warn ERESOLVE       [Object], [Object]
46 warn ERESOLVE     ]
46 warn ERESOLVE   },
46 warn ERESOLVE   peerConflict: {
46 warn ERESOLVE     current: {
46 warn ERESOLVE       name: '@babel/core',
46 warn ERESOLVE       version: '7.9.6',
46 warn ERESOLVE       location: 'node_modules/@babel/core',
46 warn ERESOLVE       isWorkspace: false,
46 warn ERESOLVE       dependents: [Array]
46 warn ERESOLVE     },
46 warn ERESOLVE     peer: {
46 warn ERESOLVE       name: '@babel/core',
46 warn ERESOLVE       version: '7.20.2',
46 warn ERESOLVE       whileInstalling: [Object],
46 warn ERESOLVE       location: 'node_modules/@babel/core',
46 warn ERESOLVE       isWorkspace: false,
46 warn ERESOLVE       dependents: [Array]
46 warn ERESOLVE     }
46 warn ERESOLVE   },
46 warn ERESOLVE   strictPeerDeps: false,
46 warn ERESOLVE   force: false,
46 warn ERESOLVE   isMine: false
46 warn ERESOLVE }
47 timing idealTree:node_modules/@babel/plugin-proposal-class-static-block Completed in 21ms
48 silly fetch manifest react@^15.0.2
49 http fetch GET 200 https://registry.npmjs.org/react 392ms (cache revalidated)
50 timing idealTree Completed in 4890ms
51 timing command:install Completed in 4901ms
52 verbose stack Error: could not resolve
52 verbose stack     at PlaceDep.failPeerConflict (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:549:25)
52 verbose stack     at PlaceDep.place (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:199:21)
52 verbose stack     at new PlaceDep (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:73:10)
52 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:990:31
52 verbose stack     at Array.map (<anonymous>)
52 verbose stack     at Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:990:8)
52 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:218:7)
52 verbose stack     at async Promise.all (index 1)
52 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
52 verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:156:5)
53 verbose cwd D:\React prime react sample\ssss\optimajet-formbuilder\demo
54 verbose Windows_NT 10.0.19044
55 verbose node v16.15.1
56 verbose npm  v8.11.0
57 error code ERESOLVE
58 error ERESOLVE could not resolve
59 error
60 error While resolving: [1mreflux[22m@[1m6.4.1[22m
60 error Found: [1mreact[22m@[1m16.13.1[22m[2m[22m
60 error [2mnode_modules/react[22m
60 error   [1mreact[22m@"[1m16.13.1[22m" from the root project
60 error   [35mpeer[39m [1mreact[22m@"[1m>=0.14.0[22m" from [1m@hypnosphi/create-react-context[22m@[1m0.3.1[22m[2m[22m
60 error   [2mnode_modules/@hypnosphi/create-react-context[22m
60 error     [1m@hypnosphi/create-react-context[22m@"[1m^0.3.1[22m" from [1mreact-popper[22m@[1m1.3.11[22m[2m[22m
60 error     [2mnode_modules/semantic-ui-react/node_modules/react-popper[22m
60 error       [1mreact-popper[22m@"[1m^1.3.3[22m" from [1msemantic-ui-react[22m@[1m0.87.3[22m[2m[22m
60 error       [2mnode_modules/semantic-ui-react[22m
60 error         [1msemantic-ui-react[22m@"[1m0.87.3[22m" from the root project
60 error   18 more (@semantic-ui-react/event-stack, draft-convert, ...)
60 error
60 error Could not resolve dependency:
60 error [35mpeer[39m [1mreact[22m@"[1m^15.0.2[22m" from [1mreflux[22m@[1m6.4.1[22m[2m[22m
60 error [2mnode_modules/reflux[22m
60 error   [1mreflux[22m@"[1m6.4.1[22m" from the root project
60 error
60 error Conflicting peer dependency: [1mreact[22m@[1m15.7.0[22m[2m[22m
60 error [2mnode_modules/react[22m
60 error   [35mpeer[39m [1mreact[22m@"[1m^15.0.2[22m" from [1mreflux[22m@[1m6.4.1[22m[2m[22m
60 error   [2mnode_modules/reflux[22m
60 error     [1mreflux[22m@"[1m6.4.1[22m" from the root project
60 error
60 error Fix the upstream dependency conflict, or retry
60 error this command with --force, or --legacy-peer-deps
60 error to accept an incorrect (and potentially broken) dependency resolution.
60 error
60 error See C:\Users\p.brooshaki\AppData\Local\npm-cache\eresolve-report.txt for a full report.
61 verbose exit 1
62 timing npm Completed in 5032ms
63 verbose unfinished npm timer reify 1667979667291
64 verbose unfinished npm timer reify:loadTrees 1667979667299
65 verbose unfinished npm timer idealTree:buildDeps 1667979667998
66 verbose unfinished npm timer idealTree:node_modules/reflux 1667979671778
67 verbose code 1
68 error A complete log of this run can be found in:
68 error     C:\Users\p.brooshaki\AppData\Local\npm-cache\_logs\2022-11-09T07_41_07_175Z-debug-0.log

**Comment by sergeythrees** [comment]
> @Boroushakihbm 
> hi has error in the 'npm install '
> 
> npm install npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead. npm WARN ERESOLVE overriding peer dependency npm WARN While resolving: @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.15.4 npm WARN Found: @babel/core@7.9.6 npm WARN node_modules/@babel/core npm WARN dev @babel/core@"7.9.6" from the root project npm WARN 76 more (@babel/helper-compilation-targets, ...) ...

Hello, try use this command, Instead of npm install:
`npm install --legacy-peer-deps`

**Comment by sergeythrees** [comment]
> @Boroushakihbm 
> hi has error in the 'npm install '

We have updated the [readme](https://github.com/optimajet/formbuilder/blob/master/README.md)

**Comment by Boroushakihbm** [comment]
> > @Boroushakihbm
> > hi has error in the 'npm install '
> 
> We have updated the [readme](https://github.com/optimajet/formbuilder/blob/master/README.md)



> > @Boroushakihbm
> > hi has error in the 'npm install '
> > npm install npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead. npm WARN ERESOLVE overriding peer dependency npm WARN While resolving: @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.15.4 npm WARN Found: @babel/core@7.9.6 npm WARN node_modules/@babel/core npm WARN dev @babel/core@"7.9.6" from the root project npm WARN 76 more (@babel/helper-compilation-targets, ...) ...
> 
> Hello, try use this command, Instead of npm install: `npm install --legacy-peer-deps`

thank you this command worked
